---
- name: INSTALL | timeshift-autosnap-apt
  block:
  - name: INSTALL | Clone timeshift-autosnap-apt repository
    ansible.builtin.git:
      repo: 'https://github.com/wmutschl/timeshift-autosnap-apt.git'
      dest: "{{ autosnap_repo_dir }}/timeshift-autosnap-apt"

  - name: INSTALL | Install timeshift-autosnap-apt
    community.general.make:
      chdir: "{{ autosnap_repo_dir }}/timeshift-autosnap-apt"
      target: install
      params:
        DESTDIR: "{{ autosnap_destdir }}"
        LIB_DIR: "{{ autosnap_lib_dir }}"
    become: true
    when: "'{{ autosnap_destdir }}/usr/bin/timeshift-autosnap-apt' is not file"
  when: ansible_facts['pkg_mgr'] == "apt"
  tags: install

- name: CONFIGURE | timeshift-autosnap-apt
  block:
    - name: CONFIGURE | snapshotBoot
      ansible.builtin.lineinfile:
        path: "{{ autosnap_destdir }}/etc/timeshift-autosnap-apt.conf"
        regexp: "^snapshotBoot="
        line: "snapshotBoot={{ snapshot_boot }}"
      become: true

    - name: CONFIGURE | snapshotEFI
      ansible.builtin.lineinfile:
        path: "{{ autosnap_destdir }}/etc/timeshift-autosnap-apt.conf"
        regexp: "^snapshotEFI="
        line: "snapshotEFI={{ snapshot_efi }}"
      become: true

    - name: CONFIGURE | skipAutosnap
      ansible.builtin.lineinfile:
        path: "{{ autosnap_destdir }}/etc/timeshift-autosnap-apt.conf"
        regexp: "^skipAutosnap="
        line: "skipAutosnap={{ skip_autosnap }}"
      become: true

    - name: CONFIGURE | deleteSnapshots
      ansible.builtin.lineinfile:
        path: "{{ autosnap_destdir }}/etc/timeshift-autosnap-apt.conf"
        regexp: "^deleteSnapshots="
        line: "deleteSnapshots={{ delete_snapshots }}"
      become: true

    - name: CONFIGURE | maxSnapshots
      ansible.builtin.lineinfile:
        path: "{{ autosnap_destdir }}/etc/timeshift-autosnap-apt.conf"
        regexp: "^maxSnapshots="
        line: "maxSnapshots={{ max_snapshots }}"
      become: true

    - name: CONFIGURE | updateGrub
      ansible.builtin.lineinfile:
        path: "{{ autosnap_destdir }}/etc/timeshift-autosnap-apt.conf"
        regexp: "^updateGrub="
        line: "updateGrub={{ update_grub }}"
      become: true

    - name: CONFIGURE | snapshotDescription
      ansible.builtin.lineinfile:
        path: "{{ autosnap_destdir }}/etc/timeshift-autosnap-apt.conf"
        regexp: "^snapshotDescription="
        line: "snapshotDescription={{ snapshot_description }}"
      become: true
  tags: configure

- name: REMOVE | timeshift-autosnap-apt
  block:
    - name: REMOVE | Remove timeshift-autosnap-apt from system
      become: true
      community.general.make:
        chdir: "{{ autosnap_repo_dir }}/timeshift-autosnap-apt"
        target: uninstall
        params:
          DESTDIR: "{{ autosnap_destdir }}"
          LIB_DIR: "{{ autosnap_lib_dir }}"
      when: "'{{ autosnap_destdir }}/usr/bin/timeshift-autosnap-apt' is file"

    - name: REMOVE | Remove timeshift-autosnap-apt repository
      ansible.builtin.file:
        path: "{{ autosnap_repo_dir }}/timeshift-autosnap-apt"
        state: absent
  tags: [remove, never]
