---
- name: INSTALL | timeshift-autosnap-apt
  block:
  - name: INSTALL | Clone timeshift-autosnap-apt repository
    ansible.builtin.git:
      repo: 'https://github.com/wmutschl/timeshift-autosnap-apt.git'
      dest: "{{ autosnap_repo_dir }}/timeshift-autosnap-apt"

  - name: INSTALL | Install timeshift-autosnap-apt
    community.general.make:
      chdir: "{{ autosnap_repo_dir }}/timeshift-autosnap-apt"
      target: install
      params:
        DESTDIR: "{{ autosnap_destdir }}"
        LIB_DIR: "{{ autosnap_lib_dir }}"
    become: true
    when: "'{{ autosnap_destdir }}/usr/bin/timeshift-autosnap-apt' is not file"
  when: ansible_facts['pkg_mgr'] == "apt"
  tags: install

- name: REMOVE | timeshift-autosnap-apt
  block:
    - name: REMOVE | Remove timeshift-autosnap-apt from system
      become: true
      community.general.make:
        chdir: "{{ autosnap_repo_dir }}/timeshift-autosnap-apt"
        target: uninstall
        params:
          DESTDIR: "{{ autosnap_destdir }}"
          LIB_DIR: "{{ autosnap_lib_dir }}"
      when: "'{{ autosnap_destdir }}/usr/bin/timeshift-autosnap-apt' is file"

    - name: REMOVE | Remove timeshift-autosnap-apt repository
      ansible.builtin.file:
        path: "{{ autosnap_repo_dir }}/timeshift-autosnap-apt"
        state: absent
  tags: [remove, never]
